name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: zf2_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, php-xml, ext-dom, pdo, mysql, zip
        coverage: none

    - name: Checkout SF2 Sample
      uses: actions/checkout@v2
      with:
        repository: Naktibalda/codeception-zf2-tests
        path: framework-tests
        ref: 4.0
        submodules: recursive

    - name: Install SF2 Sample
      run: |
        composer update -d framework-tests --no-dev --prefer-dist --no-interaction
        php ./framework-tests/vendor/bin/doctrine-module orm:schema-tool:create

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: |
        composer require codeception/module-phpbrowser --dev 
        composer install --prefer-dist --no-progress --no-interaction --no-suggest

    - name: Run test suite
      run: |
        php ./vendor/bin/codecept build -c framework-tests
        php ./vendor/bin/codecept run functional -c framework-tests
